version: '3'
services:
  seed:
    image: mhamrah/clustering:0.3
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
      QUORUM_SIZE: 4
      SEED_SIZE: 1

  c1:
    image: mhamrah/clustering:0.3
    environment:
      CLUSTER_PORT: 0
      CLUSTER_IP: ""
      SEED_PORT_1600_TCP_ADDR: seed
      QUORUM_SIZE: 4
      SEED_SIZE: 1
