version: '3.4'
services:
  seed:
    image: 10.232.128.157:5000/yiguan/clustering:0.32
    ports:
      - target: 1600
        published: 1600
        protocol: tcp
        mode: ingress
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
      QUORUM_SIZE: 4
      SEED_SIZE: 1

  c1:
    image: 10.232.128.157:5000/yiguan/clustering:0.32
    environment:
      CLUSTER_PORT: 0
      CLUSTER_IP: ""
      SEED_PORT_1600_TCP_ADDR: seed
      QUORUM_SIZE: 4
      SEED_SIZE: 1
